require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
